package ru.tsystems.ecare.persistence.entities;

// default package
// Generated 09.10.2014 13:21:52 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Contract generated by hbm2java
 */
public class Contract implements java.io.Serializable {

	private Integer number;
	private Customer customer;
	private Tariff tariff;
	private Set options = new HashSet(0);

	public Contract() {
	}

	public Contract(Customer customer, Tariff tariff) {
		this.customer = customer;
		this.tariff = tariff;
	}

	public Contract(Customer customer, Tariff tariff, Set options) {
		this.customer = customer;
		this.tariff = tariff;
		this.options = options;
	}

	public Integer getNumber() {
		return this.number;
	}

	public void setNumber(Integer number) {
		this.number = number;
	}

	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	public Tariff getTariff() {
		return this.tariff;
	}

	public void setTariff(Tariff tariff) {
		this.tariff = tariff;
	}

	public Set getOptions() {
		return this.options;
	}

	public void setOptions(Set options) {
		this.options = options;
	}

}
