package ru.tsystems.ecare.persistence.entities;
// default package
// Generated 15.10.2014 12:12:11 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Contract generated by hbm2java
 */
@Entity
@Table(name = "contract", catalog = "ECareDB")
public class Contract implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2015087676939118163L;
	private Integer number;
	private Customer customer;
	private Tariff tariff;
	private Set<Option> options = new HashSet<Option>(0);

	public Contract() {
	}

	public Contract(Customer customer, Tariff tariff) {
		this.customer = customer;
		this.tariff = tariff;
	}

	public Contract(Customer customer, Tariff tariff, Set<Option> options) {
		this.customer = customer;
		this.tariff = tariff;
		this.options = options;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "number", unique = true, nullable = false)
	public Integer getNumber() {
		return this.number;
	}

	public void setNumber(Integer number) {
		this.number = number;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "customer_id", nullable = false)
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tariff_id", nullable = false)
	public Tariff getTariff() {
		return this.tariff;
	}

	public void setTariff(Tariff tariff) {
		this.tariff = tariff;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "contract_option", catalog = "ECareDB", joinColumns = { @JoinColumn(name = "contract_number", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "option_id", nullable = false, updatable = false) })
	public Set<Option> getOptions() {
		return this.options;
	}

	public void setOptions(Set<Option> options) {
		this.options = options;
	}

}
