package ru.tsystems.ecare.persistence.entities;
// default package
// Generated 13.10.2014 11:45:52 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Customer generated by hbm2java
 */
@Entity
@Table(name = "Customer", catalog = "ECareDB", uniqueConstraints = @UniqueConstraint(columnNames = "CustomerPassport"))
public class Customer implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1352292275776530646L;
	private Integer id;
	private Person person;
	private String customerPassport;
	private Set<Contract> contracts = new HashSet<Contract>(0);

	public Customer() {
	}

	public Customer(Person person, String customerPassport) {
		this.person = person;
		this.customerPassport = customerPassport;
	}

	public Customer(Person person, String customerPassport,
			Set<Contract> contracts) {
		this.person = person;
		this.customerPassport = customerPassport;
		this.contracts = contracts;
	}

	@GenericGenerator(name = "customeridgenerator", strategy = "foreign", parameters = @Parameter(name = "property", value = "person"))
	@Id
	@GeneratedValue(generator = "customeridgenerator")
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Person getPerson() {
		return this.person;
	}

	public void setPerson(Person person) {
		this.person = person;
	}

	@Column(name = "CustomerPassport", unique = true, nullable = false, length = 45)
	public String getCustomerPassport() {
		return this.customerPassport;
	}

	public void setCustomerPassport(String customerPassport) {
		this.customerPassport = customerPassport;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customer")
	public Set<Contract> getContracts() {
		return this.contracts;
	}

	public void setContracts(Set<Contract> contracts) {
		this.contracts = contracts;
	}

}
