package ru.tsystems.ecare.persistence.entities;

// default package
// Generated 09.10.2014 13:21:52 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Option generated by hbm2java
 */
public class Option implements java.io.Serializable {

	private Integer id;
	private String optionName;
	private float rate;
	private Set optionsForId = new HashSet(0);
	private Set optionsForIncompatibleId = new HashSet(0);
	private Set tariffs = new HashSet(0);
	private Set optionsForRelatedId = new HashSet(0);
	private Set optionsForId_1 = new HashSet(0);
	private Set contracts = new HashSet(0);

	public Option() {
	}

	public Option(String optionName, float rate) {
		this.optionName = optionName;
		this.rate = rate;
	}

	public Option(String optionName, float rate, Set optionsForId,
			Set optionsForIncompatibleId, Set tariffs, Set optionsForRelatedId,
			Set optionsForId_1, Set contracts) {
		this.optionName = optionName;
		this.rate = rate;
		this.optionsForId = optionsForId;
		this.optionsForIncompatibleId = optionsForIncompatibleId;
		this.tariffs = tariffs;
		this.optionsForRelatedId = optionsForRelatedId;
		this.optionsForId_1 = optionsForId_1;
		this.contracts = contracts;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getOptionName() {
		return this.optionName;
	}

	public void setOptionName(String optionName) {
		this.optionName = optionName;
	}

	public float getRate() {
		return this.rate;
	}

	public void setRate(float rate) {
		this.rate = rate;
	}

	public Set getOptionsForId() {
		return this.optionsForId;
	}

	public void setOptionsForId(Set optionsForId) {
		this.optionsForId = optionsForId;
	}

	public Set getOptionsForIncompatibleId() {
		return this.optionsForIncompatibleId;
	}

	public void setOptionsForIncompatibleId(Set optionsForIncompatibleId) {
		this.optionsForIncompatibleId = optionsForIncompatibleId;
	}

	public Set getTariffs() {
		return this.tariffs;
	}

	public void setTariffs(Set tariffs) {
		this.tariffs = tariffs;
	}

	public Set getOptionsForRelatedId() {
		return this.optionsForRelatedId;
	}

	public void setOptionsForRelatedId(Set optionsForRelatedId) {
		this.optionsForRelatedId = optionsForRelatedId;
	}

	public Set getOptionsForId_1() {
		return this.optionsForId_1;
	}

	public void setOptionsForId_1(Set optionsForId_1) {
		this.optionsForId_1 = optionsForId_1;
	}

	public Set getContracts() {
		return this.contracts;
	}

	public void setContracts(Set contracts) {
		this.contracts = contracts;
	}

}
