package ru.tsystems.ecare.persistence.entities;
// default package
// Generated 13.10.2014 11:45:52 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Tariff generated by hbm2java
 */
@Entity
@Table(name = "Tariff", catalog = "ECareDB", uniqueConstraints = @UniqueConstraint(columnNames = "Name"))
public class Tariff implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1732563263875980289L;
	private Integer id;
	private String name;
	private float rate;
	private Set<Contract> contracts = new HashSet<Contract>(0);
	private Set<Option> options = new HashSet<Option>(0);

	public Tariff() {
	}

	public Tariff(String name, float rate) {
		this.name = name;
		this.rate = rate;
	}

	public Tariff(String name, float rate, Set<Contract> contracts,
			Set<Option> options) {
		this.name = name;
		this.rate = rate;
		this.contracts = contracts;
		this.options = options;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "Name", unique = true, nullable = false, length = 100)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "Rate", nullable = false, precision = 12, scale = 0)
	public float getRate() {
		return this.rate;
	}

	public void setRate(float rate) {
		this.rate = rate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tariff")
	public Set<Contract> getContracts() {
		return this.contracts;
	}

	public void setContracts(Set<Contract> contracts) {
		this.contracts = contracts;
	}

	@ManyToMany(fetch = FetchType.LAZY)
	@JoinTable(name = "TariffOption", catalog = "ECareDB", joinColumns = { @JoinColumn(name = "TariffId", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "OptionId", nullable = false, updatable = false) })
	public Set<Option> getOptions() {
		return this.options;
	}

	public void setOptions(Set<Option> options) {
		this.options = options;
	}

}
