package ru.tsystems.ecare.persistence.entities;
// default package
// Generated 15.10.2014 12:12:11 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Tariff generated by hbm2java.
 */
@Entity
@Table(name = "tariff", catalog = "ECareDB",
        uniqueConstraints = @UniqueConstraint(columnNames = "name"))
public class Tariff implements java.io.Serializable {

    private Integer id;
    private String name;
    private float rate;
    private Set<Option> options = new HashSet<>(0);
    private Set<Contract> contracts = new HashSet<>(0);

    public Tariff() {
    }

    public Tariff(String name, float rate) {
        this.name = name;
        this.rate = rate;
    }

    public Tariff(String name, float rate, Set<Option> options,
            final Set<Contract> newContracts) {
        this.name = name;
        this.rate = rate;
        this.options = options;
        this.contracts = newContracts;
    }

    @Id
    @GeneratedValue(strategy = IDENTITY)
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    @Column(name = "name", unique = true, nullable = false, length = 100)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "rate", nullable = false, precision = 12, scale = 0)
    public float getRate() {
        return this.rate;
    }

    public void setRate(float rate) {
        this.rate = rate;
    }

    @ManyToMany(fetch = FetchType.EAGER)
    @JoinTable(name = "tariff_option", catalog = "ECareDB", joinColumns = {
        @JoinColumn(name = "tariff_id", nullable = false, updatable = false)},
            inverseJoinColumns = {
                @JoinColumn(name = "option_id", nullable = false,
                        updatable = false)})
    public Set<Option> getOptions() {
        return this.options;
    }

    public void setOptions(Set<Option> options) {
        this.options = options;
    }

    @OneToMany(fetch = FetchType.EAGER, mappedBy = "tariff")
    public Set<Contract> getContracts() {
        return this.contracts;
    }

    public void setContracts(Set<Contract> contracts) {
        this.contracts = contracts;
    }

}
