package ru.tsystems.ecare.persistence.entities;

// default package
// Generated 09.10.2014 13:21:52 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;

/**
 * Tariff generated by hbm2java
 */
public class Tariff implements java.io.Serializable {

	private Integer id;
	private String name;
	private float rate;
	private Set contracts = new HashSet(0);
	private Set options = new HashSet(0);

	public Tariff() {
	}

	public Tariff(String name, float rate) {
		this.name = name;
		this.rate = rate;
	}

	public Tariff(String name, float rate, Set contracts, Set options) {
		this.name = name;
		this.rate = rate;
		this.contracts = contracts;
		this.options = options;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public float getRate() {
		return this.rate;
	}

	public void setRate(float rate) {
		this.rate = rate;
	}

	public Set getContracts() {
		return this.contracts;
	}

	public void setContracts(Set contracts) {
		this.contracts = contracts;
	}

	public Set getOptions() {
		return this.options;
	}

	public void setOptions(Set options) {
		this.options = options;
	}

}
